name: Rust

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Update submodules
      run: git submodule update --init
    - name: Tests
      run: bash tests/run-test.sh

